import React from 'react';
import { Footer } from '../components/Footer';
import { Card } from '../components/Card';
import { LogoIcon } from '../components/Icons';
import { useAuth } from '../contexts/AuthContext';
import { Page } from '../App';
import { ThemeToggle } from '../components/ThemeToggle';

interface TermsOfServicePageProps {
  navigateTo: (page: Page) => void;
}

export const TermsOfServicePage: React.FC<TermsOfServicePageProps> = ({ navigateTo }) => {
  const { isAuthenticated } = useAuth();
  const homePage = isAuthenticated ? 'dashboard' : 'landing';

  return (
    <div className="min-h-screen font-sans text-slate-800 dark:text-slate-300 bg-slate-50 dark:bg-slate-900 flex flex-col">
        <header className="bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl border-b border-slate-200/80 dark:border-slate-800 sticky top-0 z-20">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-3 flex justify-between items-center">
                <button onClick={() => navigateTo(homePage)} className="inline-flex items-center gap-3">
                    <LogoIcon className="h-8 w-8 text-teal-600" />
                    <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">Prism AI</h1>
                </button>
                <ThemeToggle />
            </div>
        </header>

        <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-12">
            <Card className="p-8 md:p-12 max-w-4xl mx-auto">
                <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-slate-800 dark:text-slate-100 mb-6">Terms of Service</h1>
                <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-400 leading-relaxed">
                    <p><strong>Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</strong></p>
                    <p>Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the Prism AI website (the "Service") operated by us.</p>
                    
                    <h2 className="text-xl font-bold text-slate-700 dark:text-slate-200 mt-6 mb-2">1. Acceptance of Terms</h2>
                    <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service. We reserve the right to update or change our Terms of Service at any time and you should check this page periodically.</p>
                    
                    <h2 className="text-xl font-bold text-slate-700 dark:text-slate-200 mt-6 mb-2">2. Description of Service</h2>
                    <p>Prism AI provides a user interface to interact with various third-party large language models. The user can upload files for analysis, and the Service will send the file content to the selected model provider and display the result. The accuracy and quality of the analysis depend entirely on the third-party model provider.</p>
                    
                    <h2 className="text-xl font-bold text-slate-700 dark:text-slate-200 mt-6 mb-2">3. User Conduct</h2>
                    <p>You agree not to use the Service to upload, post, email, or otherwise transmit any content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or invasive of another's privacy. You are solely responsible for the content you upload and the consequences of sharing it.</p>
                    
                    <h2 className="text-xl font-bold text-slate-700 dark:text-slate-200 mt-6 mb-2">4. Disclaimer of Warranties</h2>
                    <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranty that the Service will meet your requirements, be uninterrupted, timely, secure, or error-free. The analyses provided are generated by AI and may contain inaccuracies. You should not rely on the information provided as a substitute for professional advice.</p>
                    
                    <h2 className="text-xl font-bold text-slate-700 dark:text-slate-200 mt-6 mb-2">5. Limitation of Liability</h2>
                    <p>In no event shall Prism AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
                    
                    <p>If you have any questions about these Terms, please contact us.</p>
                </div>
            </Card>
        </main>

        <Footer navigateTo={navigateTo} />
    </div>
  );
};